spring:
  application:
    name: workload-service
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    prefer-ip-address: true

app:
  jwt:
    secret: ${JWT_SECRET}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [txId=%X{transactionId}] %-5level %logger{36} - %msg%n"