spring.datasource.url=jdbc:postgresql://localhost:5432/gymdb
spring.datasource.username=gym
spring.datasource.password=gym
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
management.endpoints.web.exposure.include=health,info,metrics,prometheus,app-info,user-stats,training-stats,system-resources
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true