spring.datasource.url=jdbc:postgresql://localhost:5432/gymdb
spring.datasource.username=gym
spring.datasource.password=gym
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
management.endpoints.web.exposure.include=health,info,metrics,prometheus,app-info,user-stats,training-stats,system-resources
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
app.jwt.secret=SkY4N1pQbXQ5V2xKcXJmNGhBNzJkR2VYbTNXcUxvTnA4RkJjVnJ6YQ==
app.jwt.expiration-ms=3600000
app.cors.allowed-origins=http://localhost:9000
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
resilience4j.circuitbreaker.instances.workloadService.sliding-window-size=10
resilience4j.circuitbreaker.instances.workloadService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.workloadService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.workloadService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.workloadService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.timelimiter.instances.workloadService.timeout-duration=3s