DROP TABLE IF EXISTS trainings         CASCADE;
DROP TABLE IF EXISTS trainee_trainer   CASCADE;
DROP TABLE IF EXISTS trainees          CASCADE;
DROP TABLE IF EXISTS trainers          CASCADE;
DROP TABLE IF EXISTS users             CASCADE;

-- ---------------------------------------------------------
-- users
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
                                     id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     first_name  VARCHAR(255) NOT NULL,
    last_name   VARCHAR(255) NOT NULL,
    username    VARCHAR(255) NOT NULL,
    password    VARCHAR(255) NOT NULL,
    is_active   BOOLEAN      NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username)
    );

-- ---------------------------------------------------------
-- trainees  (1-1 with users)
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS trainees (
                                        id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        date_of_birth DATE,
                                        address       VARCHAR(255),
    user_id       BIGINT      NOT NULL,
    CONSTRAINT uk_trainees_user_id UNIQUE (user_id),
    CONSTRAINT fk_trainees_user
    FOREIGN KEY (user_id) REFERENCES users (id)
    ON DELETE CASCADE
    );

-- ---------------------------------------------------------
-- trainers  (1-1 with users)
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS trainers (
                                        id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        specialization VARCHAR(64)  NOT NULL,       -- EnumType.STRING (TrainingType)
    user_id        BIGINT       NOT NULL,
    CONSTRAINT uk_trainers_user_id UNIQUE (user_id),
    CONSTRAINT fk_trainers_user
    FOREIGN KEY (user_id) REFERENCES users (id)
    ON DELETE CASCADE
    );

-- ---------------------------------------------------------
-- trainee_trainer  (M-N join table)
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS trainee_trainer (
                                               trainee_id BIGINT NOT NULL,
                                               trainer_id BIGINT NOT NULL,
                                               CONSTRAINT pk_trainee_trainer PRIMARY KEY (trainee_id, trainer_id),
    CONSTRAINT fk_tt_trainee
    FOREIGN KEY (trainee_id) REFERENCES trainees (id)
    ON DELETE CASCADE,
    CONSTRAINT fk_tt_trainer
    FOREIGN KEY (trainer_id) REFERENCES trainers (id)
    ON DELETE CASCADE
    );

CREATE INDEX IF NOT EXISTS idx_tt_trainer_id ON trainee_trainer (trainer_id);
-- (trainee_id already leads the composite PK, so it's indexed)

-- ---------------------------------------------------------
-- trainings
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS trainings (
                                         id                        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         trainee_id                BIGINT       NOT NULL,
                                         trainer_id                BIGINT       NOT NULL,
                                         training_name             VARCHAR(255) NOT NULL,
    training_type             VARCHAR(64)  NOT NULL,   -- EnumType.STRING (TrainingType)
    training_date             DATE         NOT NULL,
    training_duration_minutes INTEGER      NOT NULL,
    CONSTRAINT fk_trainings_trainee
    FOREIGN KEY (trainee_id) REFERENCES trainees (id)
    ON DELETE CASCADE,
    CONSTRAINT fk_trainings_trainer
    FOREIGN KEY (trainer_id) REFERENCES trainers (id)
    ON DELETE CASCADE,
    CONSTRAINT chk_trainings_duration_positive
    CHECK (training_duration_minutes > 0)
    );

CREATE INDEX IF NOT EXISTS idx_trainings_trainee_id   ON trainings (trainee_id);
CREATE INDEX IF NOT EXISTS idx_trainings_trainer_id   ON trainings (trainer_id);
CREATE INDEX IF NOT EXISTS idx_trainings_training_date ON trainings (training_date);
CREATE INDEX IF NOT EXISTS idx_trainings_training_type ON trainings (training_type);